version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    command: yarn start:dev
    tty: true
    ports: 
      - '3000:3000'
    volumes: 
      - ./src:/app/src
    networks: 
      - project_network
  

  postgres:
    container_name: project_postgres
    image: postgres:12-alpine
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - '${DB_PORT}:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
    networks: 
      - project_network

  pgadmin:
    container_name: project_pgadmin
    image: dpage/pgadmin4:5.5
    restart: always
    env_file: ./.env
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - project_network

volumes: 
  postgres:
  pgadmin:

networks:
  project_network:
    driver: bridge